package com.android.nycschool.Data.Database;

import androidx.lifecycle.MutableLiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;

import com.android.nycschool.Data.Model.School;

import java.util.List;

import io.reactivex.rxjava3.core.Observable;

/*
 * This interface is used to generate a class that will make queries to the database
 * for the school table
 * It is generated by room
 * This class was created for handling any offline data querying when the app is
 * unavailable to a wifi or cellular connection
 */

@Dao
public interface SchoolDAO {

    @Query("SELECT * FROM schools")
    Observable<List<School>> getSchools();

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    long[] insertAll(List<School> schools);
}
